# List source files in REL_POPUP_SOURCES relative to src/popup/ (the same way you want them listed in
# the auto-generated src/popup/popup.html)
declare POPUP_SOURCES=(						
			"../lib/Base.js"			
			"../lib/TmUtils.js"
			"../lib/TmConsole.js"
			"../lib/PersistentDict.js"
			"../lib/utils.js"
			"../lib/PerfProfiler.js"
			"../lib/AsyncQueue.js"
			"../lib/chromeUtils.js"
			"../lib/NormalizedTabs.js"
			"../lib/ShortcutsManager.js"
			"../lib/SettingsStore.js"
			"../lib/ScheduledJob.js"
			"../lib/PopupDockerBase.js"
			"../lib/LocalStore.js"
		# Don't include staging/staging.js unless you'r taking screenshots of TabMania for publishing
		#	"../staging/TmStaging.js"																	
			"SearchTokenizer.js"
			"SearchParser.js"
			"SearchOptimizer.js"
			"SearchQuery.js"
			"BookmarksManager.js"
			"HistoryFinder.js"
			"PopupDocker.js"
			"PopupMsgServer.js"
			"icons.js"
			"Viewer.js"
			"TabViewer.js"
			"GroupsBuilder.js"
			"ContainerViewer.js"
			"SettingsItemViewer.js"
			"SettingsCustomGroupViewer.js"
			"SettingsTabViewer.js"
			"PopupViewer.js"
			"TabsTabViewer.js"
			"TabTileViewer.js"
			"TileMenuViewer.js"
			"PopupMenuViewer.js"
			"NewTabAction.js"
			"popup.js"
)
