// CLASS TmStaging
//
// This class is only needed when staging TabMania to take screenshots, by setting
// a reliable set of tabs to use as samples. All personal identifying information
// should have been scraped (e.g. email addresses in Gmail and Yahoo Mail "title")
Classes.TmStaging = Classes.Base.subclass({

tabList:
[
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://ssl.gstatic.com/ui/v1/icons/mail/rfr/gmail.ico",
		"groupId": -1,
		"height": 641,
		"highlighted": false,
		"id": 895,
		"incognito": false,
		"index": 0,
		"mutedInfo": {
			"muted": false
		},
		"pinned": true,
		"selected": false,
		"status": "complete",
		"title": "Inbox (125) - user@gmail.com - Gmail",
		"url": "https://mail.google.com/mail/u/0/#inbox",
		"width": 1282,
		"windowId": 894
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://getpocket.com/favicon.ico",
		"groupId": -1,
		"height": 641,
		"highlighted": false,
		"id": 971,
		"incognito": false,
		"index": 25,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "Does Parkinson’s Begin in the Gut?",
		"url": "https://getpocket.com/explore/item/does-parkinson-s-begin-in-the-gut",
		"width": 1282,
		"windowId": 894
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.youtube.com/s/desktop/9ba58884/img/favicon_32.png",
		"groupId": -1,
		"height": 639,
		"highlighted": false,
		"id": 1035,
		"incognito": false,
		"index": 0,
		"mutedInfo": {
			"muted": false
		},
		"pinned": true,
		"selected": false,
		"status": "complete",
		"title": "Most Iconic Classical Music Masterpieces Everyone Knows in One Single Video - YouTube",
		"url": "https://www.youtube.com/watch?v=-7jjo8UICjQ",
		"width": 1214,
		"windowId": 1034
	},
	{
		"active": true,
		"audible": true,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.youtube.com/s/desktop/fe7279a7/img/favicon_32.png",
		"groupId": -1,
		"height": 608,
		"highlighted": true,
		"id": 1039,
		"incognito": false,
		"index": 1,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": true,
		"status": "complete",
		"title": "Csardas - Vittorio Monti - Metal Version - YouTube",
		"url": "https://www.youtube.com/watch?v=y86YOTrn0KA",
		"width": 1214,
		"windowId": 1034
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.google.com/favicon.ico",
		"groupId": -1,
		"height": 639,
		"highlighted": false,
		"id": 1042,
		"incognito": false,
		"index": 2,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "99 invisible - Google Search",
		"url": "https://www.google.com/search?q=99+invisible&rlz=1C1GCEB_enUS840US840&oq=99&aqs=chrome.0.69i59j69i57j35i39j46i131i199i291i433j46i199i291i433j69i60l2j69i61.2392j0j9&sourceid=chrome&ie=UTF-8",
		"width": 1214,
		"windowId": 1034
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://99percentinvisible.org/app/uploads/2016/06/cropped-favicon_512-32x32.png",
		"groupId": -1,
		"height": 639,
		"highlighted": false,
		"id": 1045,
		"incognito": false,
		"index": 3,
		"mutedInfo": {
			"muted": true
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "99% Invisible",
		"url": "https://99percentinvisible.org/",
		"width": 1214,
		"windowId": 1034
	},
//	{
//		"active": false,
//		"audible": false,
//		"autoDiscardable": true,
//		"discarded": false,
//		"favIconUrl": "",
//		"groupId": -1,
//		"height": 639,
//		"highlighted": false,
//		"id": 1054,
//		"incognito": false,
//		"index": 6,
//		"mutedInfo": {
//			"muted": false
//		},
//		"pinned": false,
//		"selected": false,
//		"status": "unloaded",
//		"title": "Bookmarks",
//		"url": "chrome://bookmarks/?id=687",
//		"width": 1214,
//		"windowId": 1034
//	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://venturebeat.com/wp-content/themes/vb-news/img/favicon.ico",
		"groupId": -1,
		"height": 601,
		"highlighted": false,
		"id": 1072,
		"incognito": false,
		"index": 1,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "From sci-fi to reality: Evidence that the metaverse is closer than you think | VentureBeat",
		"url": "https://venturebeat.com/2021/03/02/from-sci-fi-to-reality-evidence-that-the-metaverse-is-closer-than-you-think/",
		"width": 1229,
		"windowId": 1067
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://venturebeat.com/wp-content/themes/vb-news/img/favicon.ico",
		"groupId": -1,
		"height": 601,
		"highlighted": false,
		"id": 1650,
		"incognito": false,
		"index": 2,
		"mutedInfo": {
			"muted": false
		},
		"openerTabId": 1072,
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "How AI trained to beat Atari games could impact robotics and drug design | VentureBeat",
		"url": "https://venturebeat.com/2021/03/05/how-ai-trained-to-beat-atari-games-could-impact-robotics-and-drug-design/",
		"width": 1229,
		"windowId": 1067
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://en.wikipedia.org/static/favicon/wikipedia.ico",
		"groupId": -1,
		"height": 601,
		"highlighted": false,
		"id": 1662,
		"incognito": false,
		"index": 8,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Timeline of longest spaceflights - Wikipedia",
		"url": "https://en.wikipedia.org/wiki/Timeline_of_longest_spaceflights",
		"width": 1229,
		"windowId": 1067
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.bing.com/sa/simg/favicon-2x.ico",
		"groupId": -1,
		"height": 601,
		"highlighted": false,
		"id": 1668,
		"incognito": false,
		"index": 9,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "recent scifi movies - Bing",
		"url": "https://www.bing.com/search?q=recent%20scifi%20movies&qs=n&form=QBRE&sp=-1&pq=recent%20scifi%20movies&sc=6-19&sk=&cvid=671CF0764F1543E7B8D4113CFC16B0A8",
		"width": 1229,
		"windowId": 1067
	},
	{
		"active": true,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://pisces.bbystatic.com/image2/BestBuy_US/Gallery/favicon-32-72227.png",
		"groupId": -1,
		"height": 601,
		"highlighted": true,
		"id": 1699,
		"incognito": false,
		"index": 10,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": true,
		"status": "complete",
		"title": "Gift Ideas 2021: Best Gifts to Give This Year - Best Buy",
		"url": "https://www.bestbuy.com/site/electronics/gift-ideas/abcat0010000.c?id=abcat0010000",
		"width": 1229,
		"windowId": 1067
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://s.yimg.com/nq/nr/img/favicon_alert_0wlMxfwHpReP5CbxNQJ83MuDlzpmdOmDKfB3x5Cfm-I_v1.ico",
		"groupId": -1,
		"height": 639,
		"highlighted": false,
		"id": 1089,
		"incognito": false,
		"index": 0,
		"mutedInfo": {
			"muted": false
		},
		"pinned": true,
		"selected": false,
		"status": "complete",
		"title": "(966 unread) - user@yahoo.com - Yahoo Mail",
		"url": "https://mail.yahoo.com/d/folders/1?reason=invalid_cred",
		"width": 1214,
		"windowId": 1088
	},
	{
		"active": true,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://nautil.us/favicon.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": true,
		"id": 1099,
		"incognito": false,
		"index": 3,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": true,
		"status": "complete",
		"title": "Here's Why Most Neuroscientists Are Wrong About the Brain - Facts So Romantic - Nautilus",
		"url": "https://nautil.us/blog/heres-why-most-neuroscientists-are-wrong-about-the-brain",
		"width": 1214,
		"windowId": 1088
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"groupId": -1,
		"height": 639,
		"highlighted": false,
		"id": 1117,
		"incognito": false,
		"index": 9,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "Cybersecurity for a Remote Workforce",
		"url": "https://sloanreview.mit.edu/article/cybersecurity-for-a-remote-workforce/",
		"width": 1214,
		"windowId": 1088
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://cdn.vox-cdn.com/community_logos/52517/voxv.png",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1123,
		"incognito": false,
		"index": 11,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Pentagon UFO report: The case for taking these videos seriously - Vox",
		"url": "https://www.vox.com/policy-and-politics/2020/5/8/21244090/pentagon-ufo-report-navy-alexander-wendt",
		"width": 1214,
		"windowId": 1088
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"groupId": -1,
		"height": 607,
		"highlighted": false,
		"id": 1126,
		"incognito": false,
		"index": 12,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Covid-19 conspiracy theories are being fed to the public by institutions meant to inform them - Vox",
		"url": "https://www.vox.com/2020/7/26/21338174/covid-19-conspiracy-theories-fauci-sinclair-plandemic",
		"width": 1214,
		"windowId": 1088
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"groupId": -1,
		"height": 607,
		"highlighted": false,
		"id": 1129,
		"incognito": false,
		"index": 13,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "Four Skills Tomorrow’s Innovation Workforce Will Need",
		"url": "https://sloanreview.mit.edu/article/four-skills-tomorrows-innovation-workforce-will-need/",
		"width": 1214,
		"windowId": 1088
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"groupId": -1,
		"height": 607,
		"highlighted": false,
		"id": 1171,
		"incognito": false,
		"index": 27,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "gartner SaaS Management Platforms - Google Search",
		"url": "https://www.google.com/search?newwindow=1&safe=off&rlz=1C1GCEB_enUS840US840&sxsrf=ALeKk03kzjy-gXF1A0-gD6ZA5ZKMXTIacQ%3A1605149171051&ei=86GsX7TbAuPi9APsgpDQDg&q=gartner+SaaS+Management+Platforms&oq=gartner+SaaS+Management+Platforms&gs_lcp=CgZwc3ktYWIQAzIGCAAQBxAeMgIIADoECAAQDToICAAQBxAFEB5Q_soCWL7WAmCX2wJoAHABeACAAX2IAbgGkgEDMy41mAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=psy-ab&ved=0ahUKEwj0oJvR_vvsAhVjMX0KHWwBBOoQ4dUDCA0&uact=5",
		"width": 1214,
		"windowId": 1088
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.google.com/favicon.ico",
		"groupId": -1,
		"height": 607,
		"highlighted": false,
		"id": 1177,
		"incognito": false,
		"index": 29,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "suvee steak - Google Search",
		"url": "https://www.google.com/search?q=suvee+steak&rlz=1C1GCEB_enUS840US840&oq=suvee&aqs=chrome.1.69i57j0l5j0i10j0.3948j0j4&sourceid=chrome&ie=UTF-8",
		"width": 1214,
		"windowId": 1088
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://techcrunch.com/wp-content/uploads/2015/02/cropped-cropped-favicon-gradient.png?w=32",
		"groupId": -1,
		"height": 609,
		"highlighted": false,
		"id": 1653,
		"incognito": false,
		"index": 7,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "TechCrunch – Startup and Technology News",
		"url": "https://techcrunch.com/",
		"width": 1215,
		"windowId": 1225
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://techcrunch.com/wp-content/uploads/2015/02/cropped-cropped-favicon-gradient.png?w=32",
		"groupId": -1,
		"height": 609,
		"highlighted": false,
		"id": 1656,
		"incognito": false,
		"index": 8,
		"mutedInfo": {
			"muted": false
		},
		"openerTabId": 1653,
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Investors still love software more than life | TechCrunch",
		"url": "https://techcrunch.com/2021/03/06/investors-still-love-software-more-than-life/",
		"width": 1215,
		"windowId": 1225
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://techcrunch.com/wp-content/uploads/2015/02/cropped-cropped-favicon-gradient.png?w=32",
		"groupId": -1,
		"height": 609,
		"highlighted": false,
		"id": 1659,
		"incognito": false,
		"index": 9,
		"mutedInfo": {
			"muted": false
		},
		"openerTabId": 1653,
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "The Product Manager asterisk | TechCrunch",
		"url": "https://techcrunch.com/2021/03/06/the-product-manager-asterisk/",
		"width": 1215,
		"windowId": 1225
	},
	{
		"active": true,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://secure.img1-fg.wfcdn.com/st4/stores/common/wayfair/favicon.ico",
		"groupId": -1,
		"height": 609,
		"highlighted": true,
		"id": 1702,
		"incognito": false,
		"index": 10,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": true,
		"status": "complete",
		"title": "Bloomsbury Market Armijo Upholstered Storage Bench | Wayfair",
		"url": "https://www.wayfair.com/furniture/pdp/bloomsbury-market-armijo-upholstered-storage-bench-w000519956.html",
		"width": 1215,
		"windowId": 1225
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://aeon.co/favicon.ico",
		"groupId": -1,
		"height": 628,
		"highlighted": false,
		"id": 1625,
		"incognito": false,
		"index": 6,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Aeon | a world of ideas",
		"url": "https://aeon.co/",
		"width": 1249,
		"windowId": 1246
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://aeon.co/favicon.ico",
		"groupId": -1,
		"height": 628,
		"highlighted": false,
		"id": 1628,
		"incognito": false,
		"index": 7,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "When medicine offers no relief, a biohacker begins a radical self-experiment | Aeon Videos",
		"url": "https://aeon.co/videos/when-medicine-offers-no-relief-a-biohacker-begins-a-radical-self-experiment",
		"width": 1249,
		"windowId": 1246
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://aeon.co/favicon.ico",
		"groupId": -1,
		"height": 628,
		"highlighted": false,
		"id": 1631,
		"incognito": false,
		"index": 8,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "None of our technologies has managed to destroy humanity – yet | Aeon Essays",
		"url": "https://aeon.co/essays/none-of-our-technologies-has-managed-to-destroy-humanity-yet",
		"width": 1249,
		"windowId": 1246
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.houzz.com/favicon.ico",
		"groupId": -1,
		"height": 628,
		"highlighted": false,
		"id": 1693,
		"incognito": false,
		"index": 9,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Houzz - Home Design, Decorating and Remodeling Ideas and Inspiration, Kitchen and Bathroom Design",
		"url": "https://www.houzz.com/",
		"width": 1249,
		"windowId": 1246
	},
	{
		"active": true,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://pisces.bbystatic.com/image2/BestBuy_US/Gallery/favicon-32-72227.png",
		"groupId": -1,
		"height": 628,
		"highlighted": true,
		"id": 1696,
		"incognito": false,
		"index": 10,
		"mutedInfo": {
			"muted": false
		},
		"openerTabId": 1693,
		"pinned": false,
		"selected": true,
		"status": "complete",
		"title": "Appliance Savings Event – Best Buy",
		"url": "https://www.bestbuy.com/site/home-appliances/major-appliances-sale-event/pcmcat321600050000.c?id=pcmcat321600050000",
		"width": 1249,
		"windowId": 1246
	},
	{
		"active": true,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "chrome-extension://flhpmmboiepkmkippdhjllnejfolajdb/images/icon-16.png",
		"groupId": -1,
		"height": 835,
		"highlighted": true,
		"id": 1267,
		"incognito": false,
		"index": 0,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": true,
		"status": "complete",
		"title": "TabMania",
		"url": "chrome-extension://flhpmmboiepkmkippdhjllnejfolajdb/popup/popup.html?undocked",
		"width": 297,
		"windowId": 1266
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"groupId": -1,
		"height": 728,
		"highlighted": false,
		"id": 1308,
		"incognito": false,
		"index": 12,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "Top 10 4K Computer Monitors 2020",
		"url": "https://buyersguide.org/computer-monitors/t/4k?kw=2559636762080232669&m=e&d=c&c=426482240049&p=&oid=kwd-892358226175&lp=9032151&li=&nw=g&nts=1&gclid=Cj0KCQjwy6T1BRDXARIsAIqCTXoaA7CfSu-5vqmCTBi8EcpPvcQbYFPqvFKRwrENAWEwZyFdrKTXpmMaAnoDEALw_wcB&tdid=8418655&gclid=Cj0KCQjwy6T1BRDXARIsAIqCTXoaA7CfSu-5vqmCTBi8EcpPvcQbYFPqvFKRwrENAWEwZyFdrKTXpmMaAnoDEALw_wcB",
		"width": 1228,
		"windowId": 1270
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://vanilla.futurecdn.net/techradar/243769/favicon.ico",
		"groupId": -1,
		"height": 728,
		"highlighted": false,
		"id": 1311,
		"incognito": false,
		"index": 13,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "Best 4K Monitors 2021: the best Ultra HD screens for your PC | TechRadar",
		"url": "https://www.techradar.com/news/best-4k-monitors",
		"width": 1228,
		"windowId": 1270
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://vanilla.futurecdn.net/techradar/243082/favicon.ico",
		"groupId": -1,
		"height": 728,
		"highlighted": false,
		"id": 1314,
		"incognito": false,
		"index": 14,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "LG 27UD88-W review | TechRadar",
		"url": "https://www.techradar.com/reviews/lg-27ud88-w",
		"width": 1228,
		"windowId": 1270
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://perdoo-wpengine.netdna-ssl.com/wp-content/themes/theme/dist/images/favicons/favicon.ico",
		"groupId": -1,
		"height": 728,
		"highlighted": false,
		"id": 1323,
		"incognito": false,
		"index": 17,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "OKR - The Ultimate Guide to Objectives & Key Results",
		"url": "https://www.perdoo.com/the-ultimate-okr-guide/",
		"width": 1228,
		"windowId": 1270
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.whatmatters.com/assets/img/favicon-32x32.png",
		"groupId": -1,
		"height": 728,
		"highlighted": false,
		"id": 1329,
		"incognito": false,
		"index": 19,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "What Matters",
		"url": "https://www.whatmatters.com/",
		"width": 1228,
		"windowId": 1270
	},
	{
		"active": true,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://en.wikipedia.org/static/favicon/wikipedia.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": true,
		"id": 1356,
		"incognito": false,
		"index": 28,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": true,
		"status": "complete",
		"title": "Battle of Kyōkōji - Wikipedia",
		"url": "https://en.wikipedia.org/wiki/Battle_of_Ky%C5%8Dk%C5%8Dji",
		"width": 1214,
		"windowId": 1270
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://en.wikipedia.org/static/favicon/wikipedia.ico",
		"groupId": -1,
		"height": 728,
		"highlighted": false,
		"id": 1359,
		"incognito": false,
		"index": 29,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "European Space Agency - Wikipedia",
		"url": "https://en.wikipedia.org/wiki/European_Space_Agency",
		"width": 1228,
		"windowId": 1270
	},
//	{
//		"active": false,
//		"audible": false,
//		"autoDiscardable": true,
//		"discarded": false,
//		"favIconUrl": "https://getpocket.com/favicon.ico",
//		"groupId": -1,
//		"height": 728,
//		"highlighted": false,
//		"id": 1383,
//		"incognito": false,
//		"index": 37,
//		"mutedInfo": {
//			"muted": false
//		},
//		"pinned": false,
//		"selected": false,
//		"status": "unloaded",
//		"title": "A Brief History of Children Sent Through the Mail",
//		"url": "https://getpocket.com/explore/item/a-brief-history-of-children-sent-through-the-mail",
//		"width": 1228,
//		"windowId": 1270
//	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://getpocket.com/favicon.ico",
		"groupId": -1,
		"height": 728,
		"highlighted": false,
		"id": 1386,
		"incognito": false,
		"index": 38,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "An Existential Crisis in Neuroscience",
		"url": "https://getpocket.com/explore/item/an-existential-crisis-in-neuroscience",
		"width": 1228,
		"windowId": 1270
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.glamour.com/verso/static/glamour/assets/favicon.ico",
		"groupId": -1,
		"height": 728,
		"highlighted": false,
		"id": 1389,
		"incognito": false,
		"index": 39,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "'Revenge Bedtime Procrastination' Is Real, According to Psychologists | Glamour",
		"url": "https://www.glamour.com/story/revenge-bedtime-procrastination-is-real-according-to-psychologists?utm_source=pocket-newtab",
		"width": 1228,
		"windowId": 1270
	},
//	{
//		"active": false,
//		"audible": false,
//		"autoDiscardable": true,
//		"discarded": false,
//		"favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
//		"groupId": -1,
//		"height": 608,
//		"highlighted": false,
//		"id": 1399,
//		"incognito": false,
//		"index": 0,
//		"mutedInfo": {
//			"muted": false
//		},
//		"pinned": true,
//		"selected": false,
//		"status": "complete",
//		"title": "marcodb26/TabMania: TabMania organizes all your browser tabs across all your windows. TabMania makes windows disappear, so you can focus on just your tabs, wherever they might be on your system. Find a lost tab; group tabs in ways that are meaningful to you, not by window; use keyboard shortcuts to navigate back to a previous tab from anywhere in the system; attach specific tabs to keyboard shortcuts so they're always one keypress away from view, regardless of how many tabs in how many windows you might have open.",
//		"url": "https://github.com/marcodb26/TabMania",
//		"width": 1214,
//		"windowId": 1398
//	},
//	{
//		"active": false,
//		"audible": false,
//		"autoDiscardable": true,
//		"discarded": false,
//		"favIconUrl": "",
//		"groupId": -1,
//		"height": 608,
//		"highlighted": false,
//		"id": 1409,
//		"incognito": false,
//		"index": 3,
//		"mutedInfo": {
//			"muted": false
//		},
//		"pinned": false,
//		"selected": false,
//		"status": "complete",
//		"title": "Bookmarks",
//		"url": "chrome://bookmarks/?id=686",
//		"width": 1214,
//		"windowId": 1398
//	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://nautil.us/favicon.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1638,
		"incognito": false,
		"index": 6,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Consciousness Is Just a Feeling - Issue 98: Mind - Nautilus",
		"url": "https://nautil.us/issue/98/mind/consciousness-is-just-a-feeling",
		"width": 1214,
		"windowId": 1398
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.nytimes.com/vi-assets/static-assets/favicon-d2483f10ef688e6f89e23806b9700298.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1641,
		"incognito": false,
		"index": 7,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "The New York Times - Breaking News, US News, World News and Videos",
		"url": "https://www.nytimes.com/",
		"width": 1214,
		"windowId": 1398
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.nytimes.com/vi-assets/static-assets/favicon-d2483f10ef688e6f89e23806b9700298.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1644,
		"incognito": false,
		"index": 8,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "10 New Books We Recommend This Week - The New York Times",
		"url": "https://www.nytimes.com/2021/03/04/books/review/10-new-books-we-recommend-this-week.html?action=click&module=At%20Home&pgtype=Homepage",
		"width": 1214,
		"windowId": 1398
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.nytimes.com/vi-assets/static-assets/favicon-d2483f10ef688e6f89e23806b9700298.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1647,
		"incognito": false,
		"index": 9,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Largest Glowing Shark Species Discovered Near New Zealand - The New York Times",
		"url": "https://www.nytimes.com/2021/03/05/science/biggest-glowing-shark.html?surface=home-discovery-vi-prg&fellback=false&req_id=704198108&algo=identity&variant=no-exp&imp_id=265847199&action=click&module=Science%20%20Technology&pgtype=Homepage",
		"width": 1214,
		"windowId": 1398
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://secure.img1-fg.wfcdn.com/st4/stores/common/wayfair/favicon.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1705,
		"incognito": false,
		"index": 10,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Small Storage Benches | Wayfair",
		"url": "https://www.wayfair.com/keyword.php?keyword=small+storage+bench",
		"width": 1214,
		"windowId": 1398
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://secure.img1-fg.wfcdn.com/st4/stores/common/wayfair/favicon.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1708,
		"incognito": false,
		"index": 11,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Bed & Bath | Wayfair",
		"url": "https://www.wayfair.com/bed-bath/cat/bed-bath-c215329.html",
		"width": 1214,
		"windowId": 1398
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://static-assets.npr.org/static/images/favicon/favicon-32x32.png",
		"groupId": 576746986,
		"height": 639,
		"highlighted": false,
		"id": 1417,
		"incognito": false,
		"index": 0,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "Scientist Author Busts Myths About Exercise, Sitting And Sleep : Shots - Health News : NPR",
		"url": "https://www.npr.org/sections/health-shots/2021/01/21/959140732/just-move-scientist-author-debunks-myths-about-exercise-and-sleep?utm_source=pocket-newtab",
		"width": 1214,
		"windowId": 1416
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://lightning.od-cdn.com/static/img/favicon.bb86d660d3929b5c0c65389d6a8e8aba.ico",
		"groupId": 1249222699,
		"height": 639,
		"highlighted": false,
		"id": 1421,
		"incognito": false,
		"index": 1,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "Search results for The Age of Surveillance Capitalism - San Francisco Public Library - OverDrive",
		"url": "https://sfpl.overdrive.com/search?query=The%20Age%20of%20Surveillance%20Capitalism",
		"width": 1214,
		"windowId": 1416
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.bing.com/sa/simg/favicon-2x.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1665,
		"incognito": false,
		"index": 8,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "best bycicle - Bing",
		"url": "https://www.bing.com/search?q=best+bycicle&form=QBLH&sp=-1&ghc=1&pq=best+bycicle&sc=6-12&qs=n&sk=&cvid=8B574AEBDD0743868AC8FFD47F224BAC",
		"width": 1214,
		"windowId": 1416
	},
	{
		"active": true,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.amazon.com/favicon.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": true,
		"id": 1674,
		"incognito": false,
		"index": 9,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": true,
		"status": "complete",
		"title": "The Domestic Revolution: How the Introduction of Coal into Victorian Homes Changed Everything: Goodman, Ruth: 9781631497636: Amazon.com: Books",
		"url": "https://www.amazon.com/Domestic-Revolution-Introduction-Victorian-Everything/dp/1631497634/ref=sr_1_1?dchild=1&keywords=the+domestic+revolution&qid=1615085355&s=books&sr=1-1",
		"width": 1214,
		"windowId": 1416
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.amazon.com/favicon.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1677,
		"incognito": false,
		"index": 10,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Amazon.com: Online Shopping for Electronics, Apparel, Computers, Books, DVDs & more",
		"url": "https://www.amazon.com/ref=nav_logo",
		"width": 1214,
		"windowId": 1416
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.amazon.com/favicon.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1683,
		"incognito": false,
		"index": 11,
		"mutedInfo": {
			"muted": false
		},
		"openerTabId": 1677,
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "The Omnivore's Dilemma: A Natural History of Four Meals: Pollan, Michael: 9780143038580: Amazon.com: Books",
		"url": "https://www.amazon.com/Omnivores-Dilemma-Natural-History-Meals/dp/0143038583/?_encoding=UTF8&pd_rd_w=2htzY&pf_rd_p=852426b2-6805-4f41-bbee-02f9b0582d6f&pf_rd_r=SKXCDRDTAJRN1RDP9BX5&pd_rd_r=5ad9f116-96ce-4fea-a8f1-bdacd3d0f7ba&pd_rd_wg=PDqgl&ref_=pd_gw_crs_wish",
		"width": 1214,
		"windowId": 1416
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.amazon.com/favicon.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1686,
		"incognito": false,
		"index": 12,
		"mutedInfo": {
			"muted": false
		},
		"openerTabId": 1677,
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "The Punisher's Brain: The Evolution of Judge and Jury (Cambridge Studies in Economics, Choice, and Society): Hoffman, Morris B.: 9781107038066: Amazon.com: Books",
		"url": "https://www.amazon.com/Punishers-Brain-Evolution-Cambridge-Economics/dp/1107038065/?_encoding=UTF8&pd_rd_w=2htzY&pf_rd_p=852426b2-6805-4f41-bbee-02f9b0582d6f&pf_rd_r=SKXCDRDTAJRN1RDP9BX5&pd_rd_r=5ad9f116-96ce-4fea-a8f1-bdacd3d0f7ba&pd_rd_wg=PDqgl&ref_=pd_gw_crs_wish",
		"width": 1214,
		"windowId": 1416
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.amazon.com/favicon.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1689,
		"incognito": false,
		"index": 13,
		"mutedInfo": {
			"muted": false
		},
		"openerTabId": 1677,
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Amazon.com: A History of Childhood (0000745651666): Heywood, Colin: Books",
		"url": "https://www.amazon.com/History-Childhood-Colin-Heywood/dp/0745651666/?_encoding=UTF8&pd_rd_w=2htzY&pf_rd_p=852426b2-6805-4f41-bbee-02f9b0582d6f&pf_rd_r=SKXCDRDTAJRN1RDP9BX5&pd_rd_r=5ad9f116-96ce-4fea-a8f1-bdacd3d0f7ba&pd_rd_wg=PDqgl&ref_=pd_gw_crs_wish",
		"width": 1214,
		"windowId": 1416
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.amazon.com/favicon.ico",
		"groupId": -1,
		"height": 608,
		"highlighted": false,
		"id": 1680,
		"incognito": false,
		"index": 14,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Nature Wars: The Incredible Story of How Wildlife Comebacks Turned Backyards into Battlegrounds: Sterba, Jim: 8601400490778: Amazon.com: Books",
		"url": "https://www.amazon.com/Nature-Wars-Incredible-Comebacks-Battlegrounds/dp/0307341976/?_encoding=UTF8&pd_rd_w=2htzY&pf_rd_p=852426b2-6805-4f41-bbee-02f9b0582d6f&pf_rd_r=SKXCDRDTAJRN1RDP9BX5&pd_rd_r=5ad9f116-96ce-4fea-a8f1-bdacd3d0f7ba&pd_rd_wg=PDqgl&ref_=pd_gw_crs_wish",
		"width": 1214,
		"windowId": 1416
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.google.com/favicon.ico",
		"groupId": -1,
		"height": 633,
		"highlighted": false,
		"id": 1452,
		"incognito": false,
		"index": 0,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "custom home office - Google Search",
		"url": "https://www.google.com/search?newwindow=1&safe=off&rlz=1C1GCEB_enUS840US840&sxsrf=ALeKk01dyAs6RpReam6p0HQJ6yRG-Ogemw%3A1609184245135&ei=9TPqX6vYB4nY-wT1pr2YCQ&q=custom+home+office&oq=custom+home+office&gs_lcp=CgZwc3ktYWIQAzICCAAyAggAMgcIABAUEIcCMgoIABDJAxAUEIcCMgIIADICCAAyAggAMgIIADICCAAyAggAOgcIABCwAxBDOgUIABCRAjoLCAAQsQMQgwEQkQI6CggAELEDEBQQhwI6CAguEMcBEK8BOggIABCxAxCDAToFCAAQsQM6BwgAELEDEAo6BAgAEApQt6kXWKO5F2DxxxdoA3ACeACAAZkBiAHnCJIBAzkuM5gBAKABAaoBB2d3cy13aXrIAQrAAQE&sclient=psy-ab&ved=0ahUKEwjrpry6tvHtAhUJ7J4KHXVTD5MQ4dUDCA4&uact=5",
		"width": 1218,
		"windowId": 1451
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.houzz.com/favicon/favicon.ico",
		"groupId": -1,
		"height": 633,
		"highlighted": false,
		"id": 1456,
		"incognito": false,
		"index": 1,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "Custom Cabinets | Find Local Professionals Who Can Help With Your Custom Cabinets Project.",
		"url": "https://www.houzz.com/proMatch/cabinets/custom-cabinets?m_refid=olm_google_783532205_43646500969_kwd-295641291319&pos=&device=c&nw=g&matchtype=b&loc=9032152&loc2=&gclid=Cj0KCQiAoab_BRCxARIsANMx4S7B0vAolE6BfHTCaSKDz2McH9kFlFRxEbndKBi5vY1gkNpPJ7ogCpkaAohPEALw_wcB",
		"width": 1218,
		"windowId": 1451
	},
	{
		"active": true,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.houzz.com/favicon.ico",
		"groupId": -1,
		"height": 601,
		"highlighted": true,
		"id": 1492,
		"incognito": false,
		"index": 13,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": true,
		"status": "complete",
		"title": "Custom Home Office | Houzz",
		"url": "https://www.houzz.com/photos/custom-home-office-phbr0lbl-bl~l_52667",
		"width": 1218,
		"windowId": 1451
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.bestbuy.com/favicon.ico",
		"groupId": -1,
		"height": 654,
		"highlighted": false,
		"id": 1547,
		"incognito": false,
		"index": 6,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "KitchenAid 30\" Convertible Range Hood Stainless steel KVUB600DSS - Best Buy",
		"url": "https://www.bestbuy.com/site/kitchenaid-30-convertible-range-hood-stainless-steel/9168085.p?skuId=9168085",
		"width": 1186,
		"windowId": 1527
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://www.google.com/favicon.ico",
		"groupId": -1,
		"height": 654,
		"highlighted": false,
		"id": 1580,
		"incognito": false,
		"index": 17,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "complete",
		"title": "best shows on amazon prime - Google Search",
		"url": "https://www.google.com/search?q=best+shows+on+amazon+prime&rlz=1C1GCEB_enUS840US840&oq=best+shows+on+&aqs=chrome.0.0i20i263i433i457j0i433l3j69i57j0i131i433j0l2.3158j0j4&sourceid=chrome&ie=UTF-8",
		"width": 1186,
		"windowId": 1527
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://static.rottentomatoes.com/static/images/icons/favicon.ico",
		"groupId": -1,
		"height": 654,
		"highlighted": false,
		"id": 1583,
		"incognito": false,
		"index": 18,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "100 Best Movies on Amazon Prime (January 2021) << Rotten Tomatoes – Movie and TV News",
		"url": "https://editorial.rottentomatoes.com/guide/best-movies-on-amazon-prime-right-now/",
		"width": 1186,
		"windowId": 1527
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://static.rottentomatoes.com/static/images/icons/favicon.ico",
		"groupId": -1,
		"height": 654,
		"highlighted": false,
		"id": 1586,
		"incognito": false,
		"index": 19,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "Best Netflix Series and Shows To Watch Right Now (January 2021) << Rotten Tomatoes – Movie and TV News",
		"url": "https://editorial.rottentomatoes.com/guide/best-netflix-shows-and-movies-to-binge-watch-now/",
		"width": 1186,
		"windowId": 1527
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://static.rottentomatoes.com/static/images/icons/favicon.ico",
		"groupId": -1,
		"height": 654,
		"highlighted": false,
		"id": 1589,
		"incognito": false,
		"index": 20,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "100 Best Movies on Netflix to Watch Right Now (January 2021) << Rotten Tomatoes – Movie and TV News",
		"url": "https://editorial.rottentomatoes.com/guide/best-netflix-movies-to-watch-right-now/",
		"width": 1186,
		"windowId": 1527
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://static.rottentomatoes.com/static/images/icons/favicon.ico",
		"groupId": -1,
		"height": 654,
		"highlighted": false,
		"id": 1592,
		"incognito": false,
		"index": 21,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "The Best Apple TV+ Shows and Movies, Ranked by Tomatometer (January 2021) << Rotten Tomatoes – Movie and TV News",
		"url": "https://editorial.rottentomatoes.com/guide/apple-tv-plus-shows-and-movies-ranked/",
		"width": 1186,
		"windowId": 1527
	},
	{
		"active": false,
		"audible": false,
		"autoDiscardable": true,
		"discarded": false,
		"favIconUrl": "https://static.rottentomatoes.com/static/images/icons/favicon.ico",
		"groupId": -1,
		"height": 654,
		"highlighted": false,
		"id": 1595,
		"incognito": false,
		"index": 22,
		"mutedInfo": {
			"muted": false
		},
		"pinned": false,
		"selected": false,
		"status": "unloaded",
		"title": "The Best HBO Series of All Time Ranked << Rotten Tomatoes – Movie and TV News",
		"url": "https://editorial.rottentomatoes.com/guide/best-hbo-series-of-all-time-ranked/",
		"width": 1186,
		"windowId": 1527
	}
],

_init: function() {
	// Overriding the parent class' _init(), but calling that original function first
	Classes.Base._init.call(this);
},

}); // Classes.TmStaging

window.tmStaging = Classes.TmStaging.create();
